# Generated by Django 3.2.8 on 2022-10-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('ARTS', 'arts'), ('COMM', 'commercial'), ('SCI', 'science')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('ARTS', 'arts'), ('COMM', 'commercial'), ('SCI', 'science')], max_length=120, null=True),
        ),
    ]
