# Generated by Django 3.2.8 on 2022-10-14 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.PositiveIntegerField(default=0)),
                ('weekname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('school fees', 'SCH FEES'), ('uniforms', 'UNIFORM'), ('sport wear', 'SPORTWEAR'), ('friday wear', 'FRIDAYWEAR'), ('lab coat', 'LABCOAT'), ('cardigan', 'CARDIGAN'), ('hat', 'HAT'), ('junior waec', 'JWAEC'), ('senior waec', 'SSCE'), ('neco', 'NECO')], default='school fees', max_length=30)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(choices=[('school fees', 'SCH FEES'), ('uniforms', 'UNIFORM'), ('sport wear', 'SPORTWEAR'), ('friday wear', 'FRIDAYWEAR'), ('lab coat', 'LABCOAT'), ('cardigan', 'CARDIGAN'), ('hat', 'HAT'), ('junior waec', 'JWAEC'), ('senior waec', 'SSCE'), ('neco', 'NECO')], default='school fees', max_length=30)),
                ('amount', models.PositiveIntegerField(default=17000)),
                ('term', models.CharField(choices=[('F', 'first'), ('S', 'second'), ('T', 'third')], default='', max_length=10)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
