# Generated by Django 3.2.8 on 2022-10-05 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('fee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(choices=[('school fees', 'SCH FEES'), ('uniforms', 'UNIFORM'), ('sport wear', 'SPORTWEAR'), ('friday wear', 'FRIDAYWEAR'), ('lab coat', 'LABCOAT'), ('cardigan', 'CARDIGAN'), ('hat', 'HAT'), ('junior waec', 'JWAEC'), ('senior waec', 'SSCE'), ('neco', 'NECO')], default='school fees', max_length=30)),
                ('amount', models.PositiveIntegerField()),
                ('term', models.CharField(choices=[('F', 'first'), ('S', 'second'), ('T', 'third')], default='', max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
