# Generated by Django 3.2.8 on 2022-10-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemadmin', '0002_alter_fee_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='paid',
        ),
    ]
