# Generated by Django 3.2.8 on 2022-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemadmin', '0003_remove_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
