# Generated by Django 3.2.8 on 2022-10-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemadmin', '0004_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='gemadmin.fee'),
        ),
    ]
