# Generated by Django 3.2.8 on 2022-10-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemadmin', '0006_alter_payment_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='fee',
        ),
    ]
