# Generated by Django 3.2.8 on 2022-10-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemadmin', '0007_remove_payment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(choices=[('school fees', 'SCH FEES'), ('uniforms', 'UNIFORM'), ('sport wear', 'SPORTWEAR'), ('friday wear', 'FRIDAYWEAR'), ('lab coat', 'LABCOAT'), ('cardigan', 'CARDIGAN'), ('hat', 'HAT'), ('junior waec', 'JWAEC'), ('senior waec', 'SSCE'), ('neco', 'NECO')], default='school fees', max_length=30),
        ),
    ]
