# Generated by Django 3.2.8 on 2022-10-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemadmin', '0009_alter_payment_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.PositiveIntegerField(default=0)),
                ('weekname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.PositiveIntegerField(default=17000),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
